//go:build windows
// Code generated by go-vk from vk.xml at 2023-03-08 21:02:20.109426 +0100 CET m=+5.193042942. DO NOT EDIT.

package vk

// Win32SurfaceCreateFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkWin32SurfaceCreateFlagsKHR.html
type Win32SurfaceCreateFlagsKHR Flags
